theme: jekyll-theme-cayman
auto: true

markdown: kramdown
kramdown:
    input: GFM
rouge: true
permalink: /:title

title: 笑与不笑也就那样
url: http://www.zjlsmart.xyz
author_info: <a href="http://image.so.com/i?q=%E6%BC%AB%E7%94%BB%E5%9B%BE%E7%89%87%E5%A5%B3%E7%94%9F&src=srp">漫画图片</a>
